Assembler: assembler.o preprocessor.o utils.o errors.o
	gcc -ansi -Wall assembler.o preprocessor.o utils.o errors.o -o Assembler

assembler.o: assembler.c assembler.h preprocessor.h utils.h errors.h
	gcc -ansi -pedantic -Wall -c assembler.c

preprocessor.o: preprocessor.c preprocessor.h utils.h
	gcc -ansi -pedantic -Wall -c preprocessor.c

utils.o: utils.c utils.h errors.h
	gcc -ansi -pedantic -Wall -c utils.c

errors.o: errors.c utils.h errors.h
	gcc -ansi -pedantic -Wall -c errors.c